[build]
  base = "backend"
  command = "npm run build"
  publish = "backend/dist"
  functions = "backend/netlify/functions"

[[plugins]]
  package = "@netlify/esbuild"

  [plugins.inputs]
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets", "@nestjs/platform-socket.io"]
